// Taylor Lake Village homes for sale — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const taylorlakevillageListings: Listing[] = [
  {
    mls: '96668050',
    address: '1211 Shorewood Drive',
    city: 'Taylor Lake Village',
    state: 'Texas',
    zip: '77586',
    price: '$379,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '1962',
    subdivision: 'Timber Cove Sec 02',
    county: 'Harris',
    remarks: 'WELCOME TO THIS BEAUTIFULLY UPDATED 5 ...',
    status: 'Active',
    photo: '/assets/listings/taylor-lake-village/96668050.jpg',
    lat: 29.5769845,
    lon: -95.055331,
  },
  {
    mls: '86874145',
    address: '25 Cmdr Runco Lane',
    city: 'Taylor Lake Village',
    state: 'Texas',
    zip: '77586',
    price: '$659,000',
    beds: '3 Bedrooms',
    baths: '4 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '2021',
    subdivision: 'Taylor Lake Place',
    county: 'Harris',
    remarks: 'Waterfront !!Stunning views of Taylor Lake from th ...',
    status: 'Active',
    photo: '/assets/listings/taylor-lake-village/86874145.jpg',
    lat: 29.5769845,
    lon: -95.055331,
  },
  {
    mls: '63457170',
    address: '43 Commander Runco Lane',
    city: 'Taylor Lake Village',
    state: 'Texas',
    zip: '77586',
    price: '$750,000',
    beds: '3 Bedrooms',
    baths: '4 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '2025',
    subdivision: 'Taylor Lake Place',
    county: 'Harris',
    remarks: 'Must have appointment to walk property.Experience ...',
    status: 'Active',
    photo: '/assets/listings/taylor-lake-village/63457170.jpg',
    lat: 29.5769845,
    lon: -95.055331,
  },
]
